[package]
name = "rprocessinjection"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = {version = "0.54.0", features = ["Win32_System_Threading", "Win32_System_Memory", "Win32_System_Diagnostics_Debug", "Win32_Security"]}

[build]
target = "x86_64-pc-windows-gnu"